apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator-backend
  template:
    metadata:
      labels:
        app: calculator-backend
    spec:
      containers:
      - name: calculator-backend
        image: calculator-backend:v1.1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        env:
        - name: NODE_ENV
          value: "production"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: calculator-backend
spec:
  selector:
    app: calculator-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 8081
  type: ClusterIP
